version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    networks:
      - nodenet
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./app:/app 
      - /app/node_modules 
    command: "dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    networks:
      - nodenet
    volumes:
      - .docker/mysql/var:/var/lib/mysql
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    container_name: nginx
    build:
      context: . 
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    networks:
      - nodenet
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  node_modules: {}

networks:
  nodenet:
    driver: bridge
